In [1]:
import pandas as pd
import numpy as np

In [2]:
data_fix_bodyType=pd.read_csv('./rst/data_yulao_rolling.csv')

In [3]:
data_fix_bodyType.head()

,adcode,bodyType,id,model,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,province_rank,date_block_num,class_id,last_5_mean,last_5_std,move_1,move_2,move_3,move_4,move_5
0,310000,SUV,0,3c974920a76ac9c1,1,2016,1479.0,11.0,106.0,292.0,3,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,310000,SUV,0,3c974920a76ac9c1,2,2016,2355.0,6.0,2255.0,134.0,3,2,1,NaN,NaN,292.0,NaN,NaN,NaN,NaN
2,310000,SUV,0,3c974920a76ac9c1,3,2016,1794.0,13.0,861.0,323.0,3,3,1,NaN,NaN,134.0,292.0,NaN,NaN,NaN
3,310000,SUV,0,3c974920a76ac9c1,4,2016,1260.0,16.0,105.0,266.0,3,4,1,NaN,NaN,323.0,134.0,292.0,NaN,NaN
4,310000,SUV,0,3c974920a76ac9c1,5,2016,1148.0,28.0,2107.0,271.0,3,5,1,NaN,NaN,266.0,323.0,134.0,292.0,NaN

In [4]:
drop_columns=["last_5_mean","last_5_std","move_1","move_2","move_3","move_4","move_5"]
data_without_rubbish=pd.DataFrame()
data_without_rubbish=data_fix_bodyType.drop(drop_columns,axis=1)

In [5]:
data_without_rubbish.head()

,adcode,bodyType,id,model,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,province_rank,date_block_num,class_id
0,310000,SUV,0,3c974920a76ac9c1,1,2016,1479.0,11.0,106.0,292.0,3,1,1
1,310000,SUV,0,3c974920a76ac9c1,2,2016,2355.0,6.0,2255.0,134.0,3,2,1
2,310000,SUV,0,3c974920a76ac9c1,3,2016,1794.0,13.0,861.0,323.0,3,3,1
3,310000,SUV,0,3c974920a76ac9c1,4,2016,1260.0,16.0,105.0,266.0,3,4,1
4,310000,SUV,0,3c974920a76ac9c1,5,2016,1148.0,28.0,2107.0,271.0,3,5,1

In [6]:
data_sort=data_without_rubbish.sort_index(by=['date_block_num'])
data_sort=data_sort.reset_index()

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.

In [7]:
data_sort.head()

,index,adcode,bodyType,id,model,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,province_rank,date_block_num,class_id
0,0,310000,SUV,0,3c974920a76ac9c1,1,2016,1479.0,11.0,106.0,292.0,3,1,1
1,30268,110000,Hatchback,0,3e21824be728cbec,1,2016,1618.0,79.0,1763.0,315.0,2,1,230
2,17500,450000,SUV,0,bb9fbec9a2833839,1,2016,971.0,4.0,920.0,131.0,4,1,569
3,6048,210000,Sedan,0,7cf283430b3b5e38,1,2016,1526.0,270.0,3705.0,589.0,4,1,1090
4,30296,510000,Hatchback,0,3e21824be728cbec,1,2016,3076.0,79.0,1763.0,825.0,2,1,290

In [8]:
data_sort.loc[-5:,:]

,index,adcode,bodyType,id,model,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,province_rank,date_block_num,class_id
0,0,310000,SUV,0,3c974920a76ac9c1,1,2016,1479.0,11.0,106.0,292.0,3,1,1
1,30268,110000,Hatchback,0,3e21824be728cbec,1,2016,1618.0,79.0,1763.0,315.0,2,1,230
2,17500,450000,SUV,0,bb9fbec9a2833839,1,2016,971.0,4.0,920.0,131.0,4,1,569
3,6048,210000,Sedan,0,7cf283430b3b5e38,1,2016,1526.0,270.0,3705.0,589.0,4,1,1090
4,30296,510000,Hatchback,0,3e21824be728cbec,1,2016,3076.0,79.0,1763.0,825.0,2,1,290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36955,23827,330000,SUV,4877,936168bd4850913d,4,2018,329.5,867.8,2449.0,1238.4,1,28,879
36956,23855,420000,SUV,4878,936168bd4850913d,4,2018,151.5,867.8,2449.0,1880.3,3,28,939
36957,23883,430000,SUV,4879,936168bd4850913d,4,2018,153.2,867.8,2449.0,860.9,3,28,999
36958,23687,450000,SUV,4872,936168bd4850913d,4,2018,105.9,867.8,2449.0,449.6,4,28,579
36959,36959,230000,SUV,5368,a9a43d1a7ecbe75d,4,2018,751.9,427.3,1296.6,65.3,5,28,1320

In [9]:
train_sales=data_sort.copy()

In [13]:
# fix popularity
##### 1月
m1_12    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12), 'popularity'].values
m1_11    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11), 'popularity'].values
m1_10    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10), 'popularity'].values
m1_09    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9) , 'popularity'].values
m1_08    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8) , 'popularity'].values
m1_07    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7) , 'popularity'].values
m1_06    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==6) , 'popularity'].values

m1_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'popularity'].values * m1_12
m1_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'popularity'].values * m1_11
m1_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'popularity'].values * m1_10
m1_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'popularity'].values * m1_09
m1_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'popularity'].values * m1_08
m1_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'popularity'].values * m1_07
m1_06_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==6) , 'popularity'].values * m1_06

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1), 'popularity'] =  m1_12_volum/2 + m1_11_volum/4 + m1_10_volum/8 + \
                                                      m1_09_volum/16 + m1_08_volum/32 + m1_07_volum/64 + m1_06_volum/64

##### 2月
m2_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'popularity'].values
m2_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'popularity'].values
m2_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'popularity'].values
m2_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'popularity'].values
m2_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'popularity'].values
m2_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'popularity'].values
m2_07 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7 ) , 'popularity'].values

m2_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'popularity'].values * m2_01
m2_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'popularity'].values * m2_12
m2_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'popularity'].values * m2_11
m2_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'popularity'].values * m2_10
m2_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'popularity'].values * m2_09
m2_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'popularity'].values * m2_08
m2_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'popularity'].values * m2_07

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2), 'popularity'] =  m2_01_volum/2 + m2_12_volum/4 + m2_11_volum/8 + \
                                                      m2_10_volum/16 + m2_09_volum/32 + m2_08_volum/64 + m2_07_volum/64

##### 3月
m3_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'popularity'].values
m3_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'popularity'].values
m3_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'popularity'].values
m3_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'popularity'].values
m3_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'popularity'].values
m3_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'popularity'].values
m3_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'popularity'].values

m3_02_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2 ), 'popularity'].values * m3_02
m3_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'popularity'].values * m3_01
m3_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'popularity'].values * m3_12
m3_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'popularity'].values * m3_11
m3_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'popularity'].values * m3_10
m3_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'popularity'].values * m3_09
m3_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'popularity'].values * m3_08

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==3), 'popularity'] =  m3_02_volum/2 + m3_01_volum/4 + m3_12_volum/8 + \
                                                      m3_11_volum/16 + m3_10_volum/32 + m3_09_volum/64 + m3_08_volum/64

##### 4月
m4_03 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3 ) , 'popularity'].values
m4_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'popularity'].values
m4_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'popularity'].values
m4_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'popularity'].values
m4_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'popularity'].values
m4_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'popularity'].values
m4_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'popularity'].values

m4_03_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==3 ), 'popularity'].values * m4_03
m4_02_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2 ), 'popularity'].values * m4_02
m4_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'popularity'].values * m4_01
m4_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'popularity'].values * m4_12
m4_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'popularity'].values * m4_11
m4_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'popularity'].values * m4_10
m4_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9 ), 'popularity'].values * m4_09

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==4), 'popularity'] =  m4_03_volum/2 + m4_02_volum/4 + m4_01_volum/8 + \
                                                      m4_12_volum/16 + m4_11_volum/32 + m3_10_volum/64 + m4_09_volum/64

# train_sales[['id','popularity']].round().astype(int).to_csv('ccf_car_sales.csv', index=False)

In [14]:
# fix carCommentVolum
##### 1月
m1_12    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12), 'carCommentVolum'].values
m1_11    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11), 'carCommentVolum'].values
m1_10    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10), 'carCommentVolum'].values
m1_09    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9) , 'carCommentVolum'].values
m1_08    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8) , 'carCommentVolum'].values
m1_07    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7) , 'carCommentVolum'].values
m1_06    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==6) , 'carCommentVolum'].values

m1_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'carCommentVolum'].values * m1_12
m1_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'carCommentVolum'].values * m1_11
m1_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'carCommentVolum'].values * m1_10
m1_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'carCommentVolum'].values * m1_09
m1_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'carCommentVolum'].values * m1_08
m1_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'carCommentVolum'].values * m1_07
m1_06_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==6) , 'carCommentVolum'].values * m1_06

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1), 'carCommentVolum'] =  m1_12_volum/2 + m1_11_volum/4 + m1_10_volum/8 + \
                                                      m1_09_volum/16 + m1_08_volum/32 + m1_07_volum/64 + m1_06_volum/64

##### 2月
m2_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'carCommentVolum'].values
m2_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'carCommentVolum'].values
m2_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'carCommentVolum'].values
m2_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'carCommentVolum'].values
m2_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'carCommentVolum'].values
m2_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'carCommentVolum'].values
m2_07 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7 ) , 'carCommentVolum'].values

m2_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'carCommentVolum'].values * m2_01
m2_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'carCommentVolum'].values * m2_12
m2_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'carCommentVolum'].values * m2_11
m2_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'carCommentVolum'].values * m2_10
m2_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'carCommentVolum'].values * m2_09
m2_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'carCommentVolum'].values * m2_08
m2_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'carCommentVolum'].values * m2_07

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2), 'carCommentVolum'] =  m2_01_volum/2 + m2_12_volum/4 + m2_11_volum/8 + \
                                                      m2_10_volum/16 + m2_09_volum/32 + m2_08_volum/64 + m2_07_volum/64

##### 3月
m3_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'carCommentVolum'].values
m3_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'carCommentVolum'].values
m3_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'carCommentVolum'].values
m3_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'carCommentVolum'].values
m3_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'carCommentVolum'].values
m3_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'carCommentVolum'].values
m3_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'carCommentVolum'].values

m3_02_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2 ), 'carCommentVolum'].values * m3_02
m3_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'carCommentVolum'].values * m3_01
m3_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'carCommentVolum'].values * m3_12
m3_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'carCommentVolum'].values * m3_11
m3_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'carCommentVolum'].values * m3_10
m3_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'carCommentVolum'].values * m3_09
m3_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'carCommentVolum'].values * m3_08

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==3), 'carCommentVolum'] =  m3_02_volum/2 + m3_01_volum/4 + m3_12_volum/8 + \
                                                      m3_11_volum/16 + m3_10_volum/32 + m3_09_volum/64 + m3_08_volum/64

##### 4月
m4_03 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3 ) , 'carCommentVolum'].values
m4_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'carCommentVolum'].values
m4_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'carCommentVolum'].values
m4_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'carCommentVolum'].values
m4_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'carCommentVolum'].values
m4_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'carCommentVolum'].values
m4_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'carCommentVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'carCommentVolum'].values

m4_03_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==3 ), 'carCommentVolum'].values * m4_03
m4_02_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2 ), 'carCommentVolum'].values * m4_02
m4_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'carCommentVolum'].values * m4_01
m4_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'carCommentVolum'].values * m4_12
m4_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'carCommentVolum'].values * m4_11
m4_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'carCommentVolum'].values * m4_10
m4_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9 ), 'carCommentVolum'].values * m4_09

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==4), 'carCommentVolum'] =  m4_03_volum/2 + m4_02_volum/4 + m4_01_volum/8 + \
                                                      m4_12_volum/16 + m4_11_volum/32 + m3_10_volum/64 + m4_09_volum/64

# train_sales[['id','carCommentVolum']].round().astype(int).to_csv('ccf_car_sales.csv', index=False)

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:44: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:62: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:65: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:70: RuntimeWarning: invalid value encountered in multiply

In [15]:
# fix newsReplyVolum
##### 1月
m1_12    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12), 'newsReplyVolum'].values
m1_11    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11), 'newsReplyVolum'].values
m1_10    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10), 'newsReplyVolum'].values
m1_09    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9) , 'newsReplyVolum'].values
m1_08    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8) , 'newsReplyVolum'].values
m1_07    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7) , 'newsReplyVolum'].values
m1_06    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==6) , 'newsReplyVolum'].values

m1_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'newsReplyVolum'].values * m1_12
m1_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'newsReplyVolum'].values * m1_11
m1_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'newsReplyVolum'].values * m1_10
m1_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'newsReplyVolum'].values * m1_09
m1_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'newsReplyVolum'].values * m1_08
m1_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'newsReplyVolum'].values * m1_07
m1_06_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==6) , 'newsReplyVolum'].values * m1_06

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1), 'newsReplyVolum'] =  m1_12_volum/2 + m1_11_volum/4 + m1_10_volum/8 + \
                                                      m1_09_volum/16 + m1_08_volum/32 + m1_07_volum/64 + m1_06_volum/64

##### 2月
m2_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'newsReplyVolum'].values
m2_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'newsReplyVolum'].values
m2_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'newsReplyVolum'].values
m2_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'newsReplyVolum'].values
m2_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'newsReplyVolum'].values
m2_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'newsReplyVolum'].values
m2_07 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7 ) , 'newsReplyVolum'].values

m2_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'newsReplyVolum'].values * m2_01
m2_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'newsReplyVolum'].values * m2_12
m2_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'newsReplyVolum'].values * m2_11
m2_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'newsReplyVolum'].values * m2_10
m2_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'newsReplyVolum'].values * m2_09
m2_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'newsReplyVolum'].values * m2_08
m2_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'newsReplyVolum'].values * m2_07

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2), 'newsReplyVolum'] =  m2_01_volum/2 + m2_12_volum/4 + m2_11_volum/8 + \
                                                      m2_10_volum/16 + m2_09_volum/32 + m2_08_volum/64 + m2_07_volum/64

##### 3月
m3_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'newsReplyVolum'].values
m3_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'newsReplyVolum'].values
m3_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'newsReplyVolum'].values
m3_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'newsReplyVolum'].values
m3_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'newsReplyVolum'].values
m3_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'newsReplyVolum'].values
m3_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'newsReplyVolum'].values

m3_02_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2 ), 'newsReplyVolum'].values * m3_02
m3_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'newsReplyVolum'].values * m3_01
m3_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'newsReplyVolum'].values * m3_12
m3_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'newsReplyVolum'].values * m3_11
m3_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'newsReplyVolum'].values * m3_10
m3_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'newsReplyVolum'].values * m3_09
m3_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'newsReplyVolum'].values * m3_08

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==3), 'newsReplyVolum'] =  m3_02_volum/2 + m3_01_volum/4 + m3_12_volum/8 + \
                                                      m3_11_volum/16 + m3_10_volum/32 + m3_09_volum/64 + m3_08_volum/64

##### 4月
m4_03 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3 ) , 'newsReplyVolum'].values
m4_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'newsReplyVolum'].values
m4_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'newsReplyVolum'].values
m4_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'newsReplyVolum'].values
m4_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'newsReplyVolum'].values
m4_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'newsReplyVolum'].values
m4_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'newsReplyVolum'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'newsReplyVolum'].values

m4_03_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==3 ), 'newsReplyVolum'].values * m4_03
m4_02_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==2 ), 'newsReplyVolum'].values * m4_02
m4_01_volum = train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1 ), 'newsReplyVolum'].values * m4_01
m4_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'newsReplyVolum'].values * m4_12
m4_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'newsReplyVolum'].values * m4_11
m4_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'newsReplyVolum'].values * m4_10
m4_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9 ), 'newsReplyVolum'].values * m4_09

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==4), 'newsReplyVolum'] =  m4_03_volum/2 + m4_02_volum/4 + m4_01_volum/8 + \
                                                      m4_12_volum/16 + m4_11_volum/32 + m3_10_volum/64 + m4_09_volum/64

# train_sales[['id','newsReplyVolum']].round().astype(int).to_csv('ccf_car_sales.csv', index=False)

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide

/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:22: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: RuntimeWarning: invalid value encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:26: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:26: RuntimeWarning: invalid value encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: invalid value encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:30: RuntimeWarning: invalid value encountered in multiply
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:43: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:44: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:45: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:45: RuntimeWarning: invalid value encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:46: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:48: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: invalid value encountered in multiply
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:51: RuntimeWarning: invalid value encountered in multiply
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:62: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:63: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:64: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:65: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:66: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:67: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:68: RuntimeWarning: divide by zero encountered in true_divide
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:70: RuntimeWarning: invalid value encountered in multiply
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:71: RuntimeWarning: invalid value encountered in multiply
/home/gz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:72: RuntimeWarning: invalid value encountered in multiply

In [16]:
train_sales.loc[-5:,:]

,index,adcode,bodyType,id,model,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,province_rank,date_block_num,class_id
0,0,310000,SUV,0,3c974920a76ac9c1,1,2016,1479.000000,11.000000,106.000000,292.0,3,1,1
1,30268,110000,Hatchback,0,3e21824be728cbec,1,2016,1618.000000,79.000000,1763.000000,315.0,2,1,230
2,17500,450000,SUV,0,bb9fbec9a2833839,1,2016,971.000000,4.000000,920.000000,131.0,4,1,569
3,6048,210000,Sedan,0,7cf283430b3b5e38,1,2016,1526.000000,270.000000,3705.000000,589.0,4,1,1090
4,30296,510000,Hatchback,0,3e21824be728cbec,1,2016,3076.000000,79.000000,1763.000000,825.0,2,1,290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36955,23827,330000,SUV,4877,936168bd4850913d,4,2018,14823.059093,167.981104,8115.393341,1238.4,1,28,879
36956,23855,420000,SUV,4878,936168bd4850913d,4,2018,2180.582640,42.098003,3094.885884,1880.3,3,28,939
36957,23883,430000,SUV,4879,936168bd4850913d,4,2018,1198.956494,3079.604557,23116.807009,860.9,3,28,999
36958,23687,450000,SUV,4872,936168bd4850913d,4,2018,1339.041537,316.798834,NaN,449.6,4,28,579
36959,36959,230000,SUV,5368,a9a43d1a7ecbe75d,4,2018,490.597433,299.273227,406.966754,65.3,5,28,1320

In [ ]:
train_sales.to_csv('')

In [10]:
##### 1月
m1_12    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12), 'popularity'].values
m1_11    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11), 'popularity'].values
m1_10    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10), 'popularity'].values
m1_09    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9) , 'popularity'].values
m1_08    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8) , 'popularity'].values
m1_07    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7) , 'popularity'].values
m1_06    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'popularity'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==6) , 'popularity'].values

m1_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'popularity'].values * m1_12
m1_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'popularity'].values * m1_11
m1_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'popularity'].values * m1_10
m1_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'popularity'].values * m1_09
m1_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'popularity'].values * m1_08
m1_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'popularity'].values * m1_07
m1_06_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==6) , 'popularity'].values * m1_06

train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1), 'popularity'] =  m1_12_volum/2 + m1_11_volum/4 + m1_10_volum/8 + \
                                                      m1_09_volum/16 + m1_08_volum/32 + m1_07_volum/64 + m1_06_volum/64

In [11]:
train_sales.loc[(train_sales.regYear==2018)&(train_sales.regMonth==1)]

,index,adcode,bodyType,id,model,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,province_rank,date_block_num,class_id
31680,34856,130000,MPV,1267,f270f6a489c6a9d7,1,2018,4561.800483,45.5,654.3,525.9,2,25,777
31681,9404,340000,Sedan,336,37aa9169b575ef79,1,2018,697.156802,473.4,2200.4,434.7,3,25,316
31682,3104,310000,SUV,111,2a2ab41f8f6ff1cb,1,2018,18199.014143,449.3,3306.1,366.9,3,25,6
31683,17664,330000,SUV,631,bb9fbec9a2833839,1,2018,309.165924,94.2,78.2,1321.8,1,25,869
31684,21556,230000,Sedan,770,dff803b4024d261d,1,2018,1955.906822,707.1,599.9,472.5,5,25,1295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32995,23152,130000,Sedan,827,0797526c057dcf5b,1,2018,22078.373432,945.4,3077.7,2364.8,2,25,758
32996,1788,500000,SUV,64,2d0d2c3403909fdb,1,2018,698.484535,1006.9,244.7,177.5,4,25,1143
32997,19680,610000,MPV,703,79de4e4b24c35b04,1,2018,14606.040130,225.1,1433.6,606.7,4,25,1232
32998,7640,440000,SUV,273,8c915fe4632fb9fa,1,2018,358.057413,254.9,217.9,758.4,1,25,493
32999,12120,330000,SUV,433,b25c4e2e3856af22,1,2018,638.665851,928.4,3341.8,1284.2,1,25,860

In [ ]:
##### 1月
m1_12    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12), 'salesVolume'].values
m1_11    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11), 'salesVolume'].values
m1_10    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10), 'salesVolume'].values
m1_09    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9) , 'salesVolume'].values
m1_08    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8) , 'salesVolume'].values
m1_07    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7) , 'salesVolume'].values
m1_06    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==6) , 'salesVolume'].values

m1_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'salesVolume'].values * m1_12
m1_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'salesVolume'].values * m1_11
m1_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'salesVolume'].values * m1_10
m1_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'salesVolume'].values * m1_09
m1_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'salesVolume'].values * m1_08
m1_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'salesVolume'].values * m1_07
m1_06_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==6) , 'salesVolume'].values * m1_06

evaluation_public.loc[evaluation_public.regMonth==1, 'forecastVolum'] =  m1_12_volum/2 + m1_11_volum/4 + m1_10_volum/8 + \
                                                      m1_09_volum/16 + m1_08_volum/32 + m1_07_volum/64 + m1_06_volum/64

##### 2月
m2_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'salesVolume'].values
m2_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'salesVolume'].values
m2_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'salesVolume'].values
m2_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'salesVolume'].values
m2_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'salesVolume'].values
m2_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'salesVolume'].values
m2_07 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7 ) , 'salesVolume'].values

m2_01_volum = evaluation_public.loc[(evaluation_public.regYear==2018)&(evaluation_public.regMonth==1 ), 'forecastVolum'].values * m2_01
m2_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'salesVolume'].values * m2_12
m2_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'salesVolume'].values * m2_11
m2_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'salesVolume'].values * m2_10
m2_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'salesVolume'].values * m2_09
m2_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'salesVolume'].values * m2_08
m2_07_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'salesVolume'].values * m2_07

evaluation_public.loc[evaluation_public.regMonth==2, 'forecastVolum'] =  m2_01_volum/2 + m2_12_volum/4 + m2_11_volum/8 + \
                                                      m2_10_volum/16 + m2_09_volum/32 + m2_08_volum/64 + m2_07_volum/64

##### 3月
m3_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'salesVolume'].values
m3_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'salesVolume'].values
m3_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'salesVolume'].values
m3_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'salesVolume'].values
m3_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'salesVolume'].values
m3_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'salesVolume'].values
m3_08 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8 ) , 'salesVolume'].values

m3_02_volum = evaluation_public.loc[(evaluation_public.regYear==2018)&(evaluation_public.regMonth==2 ), 'forecastVolum'].values * m3_02
m3_01_volum = evaluation_public.loc[(evaluation_public.regYear==2018)&(evaluation_public.regMonth==1 ), 'forecastVolum'].values * m3_01
m3_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'salesVolume'].values * m3_12
m3_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'salesVolume'].values * m3_11
m3_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'salesVolume'].values * m3_10
m3_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'salesVolume'].values * m3_09
m3_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'salesVolume'].values * m3_08

evaluation_public.loc[evaluation_public.regMonth==3, 'forecastVolum'] =  m3_02_volum/2 + m3_01_volum/4 + m3_12_volum/8 + \
                                                      m3_11_volum/16 + m3_10_volum/32 + m3_09_volum/64 + m3_08_volum/64

##### 4月
m4_03 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3 ) , 'salesVolume'].values
m4_02 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2 ) , 'salesVolume'].values
m4_01 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1 ) , 'salesVolume'].values
m4_12 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12) , 'salesVolume'].values
m4_11 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11) , 'salesVolume'].values
m4_10 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10) , 'salesVolume'].values
m4_09 = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9 ) , 'salesVolume'].values

m4_03_volum = evaluation_public.loc[(evaluation_public.regYear==2018)&(evaluation_public.regMonth==3 ), 'forecastVolum'].values * m4_03
m4_02_volum = evaluation_public.loc[(evaluation_public.regYear==2018)&(evaluation_public.regMonth==2 ), 'forecastVolum'].values * m4_02
m4_01_volum = evaluation_public.loc[(evaluation_public.regYear==2018)&(evaluation_public.regMonth==1 ), 'forecastVolum'].values * m4_01
m4_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'salesVolume'].values * m4_12
m4_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'salesVolume'].values * m4_11
m4_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'salesVolume'].values * m4_10
m4_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9 ), 'salesVolume'].values * m4_09

evaluation_public.loc[evaluation_public.regMonth==4, 'forecastVolum'] =  m4_03_volum/2 + m4_02_volum/4 + m4_01_volum/8 + \
                                                      m4_12_volum/16 + m4_11_volum/32 + m3_10_volum/64 + m4_09_volum/64

evaluation_public[['id','forecastVolum']].round().astype(int).to_csv('ccf_car_sales.csv', index=False)