In [1]:
#写在前面，感谢林大佬的开源数据处理，其次感谢鱼老的lgb参数，我的工作其实就是把他们的代码整合一起了。
#作者- - - - Ambromse
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error as mse
#import xgboost as xgb
#import catboost as ctb

In [2]:
#请看林大佬的开源base
path = './ccf_car/'

train_sales_data = pd.read_csv(path + 'train_sales_data.csv')
train_search_data = pd.read_csv(path + 'train_search_data.csv')
train_user_reply_data = pd.read_csv(path + 'train_user_reply_data.csv')

test = pd.read_csv(path + '/evaluation_public.csv')

data = pd.concat([train_sales_data, test], ignore_index=True)
data = data.merge(train_search_data, 'left', on=['province', 'adcode', 'model', 'regYear', 'regMonth'])
data = data.merge(train_user_reply_data, 'left', on=['model', 'regYear', 'regMonth'])
data['label'] = data['salesVolume']
data['id'] = data['id'].fillna(0).astype(int)
del data['salesVolume'], data['forecastVolum']

num_feat = ['adcode', 'regMonth', 'regYear', 'popularity', 'carCommentVolum', 'newsReplyVolum']
cate_feat = ['bodyType', 'model', 'province']

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # Remove the CWD from sys.path while we load stuff.

In [3]:
data.head()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label
0,310000,SUV,0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0,292.0
1,530000,SUV,0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0,466.0
2,150000,SUV,0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0,257.0
3,110000,SUV,0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0,408.0
4,510000,SUV,0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0,610.0

In [4]:
num_feat = ['adcode', 'regMonth', 'regYear', 'popularity', 'carCommentVolum', 'newsReplyVolum']
cate_feat = ['bodyType', 'model', 'province']

for i in cate_feat:
    data[i] = data[i].astype('category')
features = num_feat + cate_feat

In [5]:
data.head()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label
0,310000,SUV,0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0,292.0
1,530000,SUV,0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0,466.0
2,150000,SUV,0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0,257.0
3,110000,SUV,0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0,408.0
4,510000,SUV,0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0,610.0

In [6]:
data.nunique()

adcode               22
bodyType              4
id                 5281
model                60
province             22
regMonth             12
regYear               3
popularity         7239
carCommentVolum     571
newsReplyVolum     1159
label              2965
dtype: int64

In [7]:
data.dtypes

adcode                int64
bodyType           category
id                    int32
model              category
province           category
regMonth              int64
regYear               int64
popularity          float64
carCommentVolum     float64
newsReplyVolum      float64
label               float64
dtype: object

In [8]:
print(train_sales_data.shape)
print(data.shape)

(31680, 7)
(36960, 11)

In [9]:
train = data[:31680]
y_label = train['label']
test = data[31680:]

drop_features = ['label']
train = train.drop(drop_features,axis=1)
test = test.drop(drop_features,axis=1)

In [10]:
train.shape
print(type(y_label))
train.head()

<class 'pandas.core.series.Series'>

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum
0,310000,SUV,0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0
1,530000,SUV,0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0
2,150000,SUV,0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0
3,110000,SUV,0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0
4,510000,SUV,0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0

In [11]:
#from sklearn.model_selection import KFold,StratifiedKFold

In [ ]:
#此处请看鱼老知乎

#开始训练
import time
since = time.time()

x_score = []
import lightgbm as lgb
from sklearn.model_selection import KFold,StratifiedKFold
from sklearn.metrics import f1_score
random_seed = 2018
#lgb_clf = lgb.LGBMClassifier(boosting_type='gbdt', num_leaves=395, max_depth=-1, learning_rate=0.1, n_estimators=5000, max_bin=425, subsample_for_bin=50000, objective='binary', min_split_gain=0,min_child_weight=5, min_child_samples=5, subsample=0.8, subsample_freq=1,colsample_bytree=0.8, reg_alpha=3, reg_lambda=5, seed=1000, n_jobs=-1, silent=True)
lgb_clf = lgb.LGBMRegressor(boosting_type='gbdt', num_leaves=48, max_depth=-1, learning_rate=0.01, n_estimators=5000,
                             max_bin=425, subsample_for_bin=50000, objective='regression_l1', min_split_gain=0,min_child_weight=5,
                             min_child_samples=10, subsample=0.8, subsample_freq=1,colsample_bytree=0.8,
                             reg_alpha=3, reg_lambda=0.1, seed=1000, n_jobs=-1, silent=True)

skf = StratifiedKFold(n_splits=5, random_state=random_seed, shuffle=True)
baseloss = []
loss = 0

res_prob = pd.DataFrame()
res = pd.DataFrame()
for i, (train_index, test_index) in enumerate(skf.split(train,y_label)):
    print("Fold", i)
    x_valid,y_valid = train.loc[test_index],y_label.loc[test_index]
    lgb_model = lgb_clf.fit(train.loc[train_index],y_label.loc[train_index],
                            eval_names=['train', 'valid'],
                            eval_metric='mae',                              
                            eval_set=[(train.loc[train_index], y_label.loc[train_index]),   
                                      (train.loc[test_index], y_label.loc[test_index])],early_stopping_rounds=100,verbose = 250)
    x_pred = lgb_model.predict(x_valid, num_iteration=lgb_model.best_iteration_)
    test_pred = lgb_model.predict(test, num_iteration=lgb_model.best_iteration_)
    res['prob_%s' % str(i)] = test_pred
print('logloss:', baseloss, loss / 5)

time_elapsed = time.time() - since
print('complete in {:.0f}m {:.0f}s'.format(time_elapsed // 60, time_elapsed % 60)) # 打印出来时间

C:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)

Fold 0
Training until validation scores don't improve for 100 rounds.
[250]	train's l1: 201.148	train's l1: 201.148	valid's l1: 202.443	valid's l1: 202.443
[500]	train's l1: 160.367	train's l1: 160.367	valid's l1: 165.325	valid's l1: 165.325
[750]	train's l1: 141.234	train's l1: 141.234	valid's l1: 148.735	valid's l1: 148.735
[1000]	train's l1: 127.101	train's l1: 127.101	valid's l1: 136.772	valid's l1: 136.772
[1250]	train's l1: 117.241	train's l1: 117.241	valid's l1: 128.94	valid's l1: 128.94
[1500]	train's l1: 110.036	train's l1: 110.036	valid's l1: 123.266	valid's l1: 123.266
[1750]	train's l1: 104.35	train's l1: 104.35	valid's l1: 118.832	valid's l1: 118.832
[2000]	train's l1: 99.7924	train's l1: 99.7924	valid's l1: 115.323	valid's l1: 115.323
[2250]	train's l1: 95.7769	train's l1: 95.7769	valid's l1: 112.324	valid's l1: 112.324
[2500]	train's l1: 92.3746	train's l1: 92.3746	valid's l1: 109.762	valid's l1: 109.762
[2750]	train's l1: 89.113	train's l1: 89.113	valid's l1: 107.515	valid's l1: 107.515
[3000]	train's l1: 86.4269	train's l1: 86.4269	valid's l1: 105.807	valid's l1: 105.807
[3250]	train's l1: 83.9898	train's l1: 83.9898	valid's l1: 104.185	valid's l1: 104.185
[3500]	train's l1: 81.8418	train's l1: 81.8418	valid's l1: 102.766	valid's l1: 102.766
[3750]	train's l1: 80.046	train's l1: 80.046	valid's l1: 101.568	valid's l1: 101.568
[4000]	train's l1: 78.6183	train's l1: 78.6183	valid's l1: 100.652	valid's l1: 100.652
[4250]	train's l1: 77.2162	train's l1: 77.2162	valid's l1: 99.8002	valid's l1: 99.8002
[4500]	train's l1: 75.8713	train's l1: 75.8713	valid's l1: 98.9086	valid's l1: 98.9086
[4750]	train's l1: 74.6729	train's l1: 74.6729	valid's l1: 98.2255	valid's l1: 98.2255
[5000]	train's l1: 73.5108	train's l1: 73.5108	valid's l1: 97.5425	valid's l1: 97.5425
Did not meet early stopping. Best iteration is:
[5000]	train's l1: 73.5108	train's l1: 73.5108	valid's l1: 97.5425	valid's l1: 97.5425
Fold 1
Training until validation scores don't improve for 100 rounds.
[250]	train's l1: 201.455	train's l1: 201.455	valid's l1: 211.688	valid's l1: 211.688
[500]	train's l1: 160.944	train's l1: 160.944	valid's l1: 172.953	valid's l1: 172.953
[750]	train's l1: 140.967	train's l1: 140.967	valid's l1: 154.272	valid's l1: 154.272
[1000]	train's l1: 128.351	train's l1: 128.351	valid's l1: 142.967	valid's l1: 142.967
[1250]	train's l1: 118.328	train's l1: 118.328	valid's l1: 134.295	valid's l1: 134.295
[1500]	train's l1: 110.844	train's l1: 110.844	valid's l1: 127.773	valid's l1: 127.773
[1750]	train's l1: 105.109	train's l1: 105.109	valid's l1: 122.786	valid's l1: 122.786
[2000]	train's l1: 100.299	train's l1: 100.299	valid's l1: 118.707	valid's l1: 118.707
[2250]	train's l1: 95.9012	train's l1: 95.9012	valid's l1: 114.999	valid's l1: 114.999
[2500]	train's l1: 92.5145	train's l1: 92.5145	valid's l1: 112.191	valid's l1: 112.191
[2750]	train's l1: 89.613	train's l1: 89.613	valid's l1: 109.966	valid's l1: 109.966
[3000]	train's l1: 87.0432	train's l1: 87.0432	valid's l1: 107.951	valid's l1: 107.951
[3250]	train's l1: 84.8976	train's l1: 84.8976	valid's l1: 106.241	valid's l1: 106.241
[3500]	train's l1: 82.8711	train's l1: 82.8711	valid's l1: 104.734	valid's l1: 104.734
[3750]	train's l1: 81.0149	train's l1: 81.0149	valid's l1: 103.262	valid's l1: 103.262
[4000]	train's l1: 79.4059	train's l1: 79.4059	valid's l1: 102.059	valid's l1: 102.059
[4250]	train's l1: 77.8504	train's l1: 77.8504	valid's l1: 100.869	valid's l1: 100.869
[4500]	train's l1: 76.4227	train's l1: 76.4227	valid's l1: 99.8335	valid's l1: 99.8335
[4750]	train's l1: 75.0539	train's l1: 75.0539	valid's l1: 98.8513	valid's l1: 98.8513
[5000]	train's l1: 73.8585	train's l1: 73.8585	valid's l1: 97.9763	valid's l1: 97.9763
Did not meet early stopping. Best iteration is:
[5000]	train's l1: 73.8585	train's l1: 73.8585	valid's l1: 97.9763	valid's l1: 97.9763
Fold 2
Training until validation scores don't improve for 100 rounds.
[250]	train's l1: 201.686	train's l1: 201.686	valid's l1: 206.491	valid's l1: 206.491
[500]	train's l1: 161.065	train's l1: 161.065	valid's l1: 169.906	valid's l1: 169.906
[750]	train's l1: 141.904	train's l1: 141.904	valid's l1: 152.737	valid's l1: 152.737
[1000]	train's l1: 128.94	train's l1: 128.94	valid's l1: 141.542	valid's l1: 141.542
[1250]	train's l1: 118.691	train's l1: 118.691	valid's l1: 132.882	valid's l1: 132.882
[1500]	train's l1: 111.269	train's l1: 111.269	valid's l1: 126.549	valid's l1: 126.549
[1750]	train's l1: 104.711	train's l1: 104.711	valid's l1: 121.299	valid's l1: 121.299
[2000]	train's l1: 99.4477	train's l1: 99.4477	valid's l1: 117.124	valid's l1: 117.124

In [ ]:
testsub = pd.read_csv(path + '/evaluation_public.csv')
testsub.head()
sum_proba = res.sum(axis=1) / 5.0
testsub['forecastVolum'] = sum_proba
testsub['forecastVolum'] = testsub[['forecastVolum']].astype(int)
testsub['forecastVolum'][testsub['forecastVolum']<0] =  0
testsub[['id','forecastVolum']].to_csv('E:/ccf/output/submmision.csv',header=True,index=None)