In [1]:
import numpy as np
import pandas as pd
import os 
import gc
from tqdm import tqdm, tqdm_notebook
from scipy.stats import skew  # for some statistics
from scipy.special import boxcox1p
from scipy.stats import boxcox_normmax
from sklearn.linear_model import ElasticNetCV, LassoCV, RidgeCV
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import KFold, cross_val_score, StratifiedKFold
from sklearn.metrics import mean_squared_error, f1_score, roc_auc_score
from mlxtend.regressor import StackingCVRegressor
import datetime
import time
import lightgbm as lgb
import xgboost as xgb

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings('ignore')

pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

# baseline

## 读取数据&数据集说明
1. [训练集]历史销量数据：train_sales_data_v1.csv

|字段名称|	字段类型	|字段说明
|--|--|--|
|province	|String|	省份|
|adcode	int	省份编码
|model|	String|	车型编码|
|bodyType|	String|	车身类型|
|regYear|	int|	年|
|regMonth|	int|	月|
|salesVolume|	int|	销量|

2. [训练集]车型搜索数据：train_search_data_v1.csv

|字段名称|	字段类型	|字段说明
|--|--|--|
|province|	String|	省份|
|adcode|	int|	省份编码|
|model|	String|	车型编码|
|regYear|	int|	年|
|regMonth|	int|	月|
|popularity|	int|	搜索量|

3. [训练集]汽车垂直媒体新闻评论数据和车型评论数据：train_user_reply_data_v1.csv

该数据集包含了垂直媒体中，各车型的每月（不分地域）论坛发帖数据、每月新闻评论数据、车型下的评论数据三部分，这三个数据没有任何包含关系。

|字段名称|	字段类型	|字段说明
|--|--|--|
|model|	String|	车型编码|
|regYear|	int|	年|
|regMonth|	int|	月|
|newsReplyVolum|	int|	对车型相关新闻文章的评论数量|
|carCommentVolum|	int|	对车型的评价数量|

4. [评测集]2018年1月至4月的各车型各省份销量预测：evaluation_public.csv

|字段名称|	字段类型	|字段说明|
|--|--|--|
|id|	int|	数据的唯一标识，不可更改|
|province|	String|	省份|
|adcode|	int|	省份编码改|
|model|	String|	车型编码|
|bodyType|	String|	车身类型|
|regYear|	int|	年|
|regMonth|	int|	月|
|forecastVolum|	int|	预测销量，参赛队伍使用建立的模型得出的销量预测结果|

In [2]:
path  = './ccf_car/'

train_sales  = pd.read_csv(path+'train_sales_data.csv')#历史销量数据
train_search = pd.read_csv(path+'train_search_data.csv')#车型搜索数据
train_user   = pd.read_csv(path+'train_user_reply_data.csv')#汽车垂直媒体新闻评论数据和车型评论数据

evaluation_public = pd.read_csv(path+'evaluation_public.csv')#2018年1月至4月的各车型各省份销量预测
submit_example    = pd.read_csv(path+'submit_example.csv')

## 规则解决方案

In [4]:
m1_12    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==12), 'salesVolume'].values
m1_11    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==11), 'salesVolume'].values
m1_10    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==10), 'salesVolume'].values
m1_09    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==9) , 'salesVolume'].values
m1_08    = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==8) , 'salesVolume'].values

m1_12_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==12), 'salesVolume'].values * m1_12
m1_11_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==11), 'salesVolume'].values * m1_11
m1_10_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==10), 'salesVolume'].values * m1_10
m1_09_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==9) , 'salesVolume'].values * m1_09
m1_08_volum = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==8) , 'salesVolume'].values * m1_08

evaluation_public.loc[evaluation_public.regMonth==1, 'forecastVolum'] =  m1_12_volum/2 + m1_11_volum/4 + m1_10_volum/8 + m1_09_volum/16 + m1_08_volum/16

In [5]:
m16_1_2  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==2) , 'salesVolume'].values
m16_1_3  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==3) , 'salesVolume'].values
m16_1_4  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==4) , 'salesVolume'].values
m16_1_5  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==5) , 'salesVolume'].values

m16_2_3  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==3) , 'salesVolume'].values
m16_2_4  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==4) , 'salesVolume'].values
m16_2_5  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==5) , 'salesVolume'].values
m16_2_6  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==6) , 'salesVolume'].values

m16_3_4  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==4) , 'salesVolume'].values
m16_3_5  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==5) , 'salesVolume'].values
m16_3_6  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==6) , 'salesVolume'].values
m16_3_7  = train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2016)&(train_sales.regMonth==7) , 'salesVolume'].values

m17_1_2  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values
m17_1_3  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values
m17_1_4  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values
m17_1_5  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==5) , 'salesVolume'].values


m17_2_3  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values
m17_2_4  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values
m17_2_5  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==5) , 'salesVolume'].values
m17_2_6  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==6) , 'salesVolume'].values

m17_3_4  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==4) , 'salesVolume'].values
m17_3_5  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==5) , 'salesVolume'].values
m17_3_6  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==6) , 'salesVolume'].values
m17_3_7  = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==7) , 'salesVolume'].values

m16_1 = m16_1_2/2 + m16_1_3/4 + m16_1_4/8 + m16_1_5/8
m16_2 = m16_2_3/2 + m16_2_4/4 + m16_2_5/8 + m16_2_6/8
m16_3 = m16_3_4/2 + m16_3_5/4 + m16_3_6/8 + m16_3_7/8

m17_1 = m17_1_2/2 + m17_1_3/4 + m17_1_4/8 + m17_1_5/8
m17_2 = m17_2_3/2 + m17_2_4/4 + m17_2_5/8 + m17_2_6/8
m17_3 = m17_3_4/2 + m17_3_5/4 + m17_3_6/8 + m17_3_7/8

m1 = m16_1 * 0.4 +  m17_1 * 0.6
m2 = m16_2 * 0.4 +  m17_2 * 0.6
m3 = m16_3 * 0.4 +  m17_3 * 0.6

evaluation_public.loc[evaluation_public.regMonth==2, 'forecastVolum'] = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==1) , 'salesVolume'].values / m1
evaluation_public.loc[evaluation_public.regMonth==3, 'forecastVolum'] = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==2) , 'salesVolume'].values / m2
evaluation_public.loc[evaluation_public.regMonth==4, 'forecastVolum'] = train_sales.loc[(train_sales.regYear==2017)&(train_sales.regMonth==3) , 'salesVolume'].values / m3

In [7]:
print(train_sales.loc[(train_sales.regMonth<=4) ,'salesVolume'].mean())
print(evaluation_public['forecastVolum'].mean())
evaluation_public[['id','forecastVolum']].round().astype(int).to_csv('ccf_car_sales.csv', index=False)

524.1121212121212
477.4628274411716

## 模型解决方案

In [3]:
data = pd.concat([train_sales, evaluation_public], ignore_index=True)#合并训练集和测试集
data = data.merge(train_search, 'left', on=['province', 'adcode', 'model', 'regYear', 'regMonth'])#将搜索数据与销量数据融合
data = data.merge(train_user, 'left', on=['model', 'regYear', 'regMonth'])#将评论数据与销量数据、搜索数据融合
data['label'] = data['salesVolume']#训练集的销量->label
data['id'] = data['id'].fillna(0).astype(int)#训练集的数据没有id，全部补零（测试集有id，范围为0~5368），id是最后需要提交的两列数据之一（另一个是forecastVolum）
del data['salesVolume'], data['forecastVolum']#salesVolume->label,forecastVolum目前全为0没有意义，故删去

num_feat = ['adcode', 'regMonth', 'regYear', 'popularity', 'carCommentVolum', 'newsReplyVolum']#number_feature数字特征
cate_feat = ['bodyType', 'model', 'province']#categlory_feature类别特征

for i in cate_feat:
    data[i] = data[i].astype('category')#都转化为类别类型
features = num_feat + cate_feat#所有特征=数字特征+类别特征

In [25]:
from sklearn.metrics import mean_squared_error as mse
def get_predict_w(model, data, label='label', feature=[], cate_feature=[], random_state=2018, n_splits=5,
                  model_type='lgb'):
    if 'sample_weight' not in data.keys():
        data['sample_weight'] = 1
    model.random_state = random_state
    predict_label = 'predict_' + label#设定需要预测量的标签
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)#K折验证
    data[predict_label] = 0#设定预测量的初始值
    test_index = (data[label].isnull()) | (data[label] == -1)#获得测试集索引，测试集的label都为NaN，所以利用data[label].isnull()实现索引
    train_data = data[~test_index].reset_index(drop=True)#获得训练集数据
    test_data = data[test_index]#获得测试集

    for train_idx, val_idx in kfold.split(train_data):#对训练集的K折分别训练
        model.random_state = model.random_state + 1
        #划分训练集
        train_x = train_data.loc[train_idx][feature]
        train_y = train_data.loc[train_idx][label]
        #划分测试集
        test_x = train_data.loc[val_idx][feature]
        test_y = train_data.loc[val_idx][label]
        if model_type == 'lgb':#LightGBM
            try:
                model.fit(train_x, train_y, eval_set=[(test_x, test_y)], early_stopping_rounds=100,
                          eval_metric='mae',
                          # callbacks=[lgb.reset_parameter(learning_rate=lambda iter: max(0.005, 0.5 * (0.99 ** iter)))],
                          categorical_feature=cate_feature,
                          sample_weight=train_data.loc[train_idx]['sample_weight'],
                          verbose=100)
            except:
                model.fit(train_x, train_y, eval_set=[(test_x, test_y)], early_stopping_rounds=100,
                          eval_metric='mae',
                          # callbacks=[lgb.reset_parameter(learning_rate=lambda iter: max(0.005, 0.5 * (0.99 ** iter)))],
                          # categorical_feature=cate_feature,
                          sample_weight=train_data.loc[train_idx]['sample_weight'],
                          verbose=100)
        elif model_type == 'ctb':#CatBoost
            model.fit(train_x, train_y, eval_set=[(test_x, test_y)], early_stopping_rounds=100,
                      # eval_metric='mae',
                      # callbacks=[lgb.reset_parameter(learning_rate=lambda iter: max(0.005, 0.5 * (0.99 ** iter)))],
                      cat_features=cate_feature,
                      sample_weight=train_data.loc[train_idx]['sample_weight'],
                      verbose=100)
        train_data.loc[val_idx, predict_label] = model.predict(test_x)#预测交叉验证中的验证集，获得最终结果，用于后续loss结果评估
        if len(test_data) != 0:
            test_data[predict_label] = test_data[predict_label] + model.predict(test_data[feature])#叠加
    test_data[predict_label] = test_data[predict_label] / n_splits#平均获得最终结果
    print(mse(train_data[label], train_data[predict_label]) * 5, train_data[predict_label].mean(),
          test_data[predict_label].mean())

    return pd.concat([train_data, test_data], sort=True, ignore_index=True), predict_label

In [21]:
lgb_model = lgb.LGBMRegressor(
    num_leaves=32, reg_alpha=0., reg_lambda=0.01, objective='mse', metric='mae',
    max_depth=-1, learning_rate=0.05, min_child_samples=20,
    n_estimators=1000, subsample=0.7, colsample_bytree=0.7, subsample_freq=1,
)#定义LightGBM模型
data, predict_label = get_predict_w(lgb_model, data, label='label',
                                    feature=features, cate_feature=cate_feat,
                                    random_state=2019, n_splits=5)#训练获得结果data和label

data['lgb'] = data[predict_label]#重命名结果标签

data['forecastVolum'] = data['lgb'].apply(lambda x: 0 if x < 0 else x)#<0的结果变为0
data[data.label.isnull()][['id', 'forecastVolum']].round().astype(int).to_csv('ccf_car_sales_lgb.csv', index=False)#输出

Training until validation scores don't improve for 100 rounds.
[100]	valid_0's l1: 167.527
[200]	valid_0's l1: 133.839
[300]	valid_0's l1: 116.699
[400]	valid_0's l1: 107.595
[500]	valid_0's l1: 101.532
[600]	valid_0's l1: 97.285
[700]	valid_0's l1: 94.0742
[800]	valid_0's l1: 91.5989
[900]	valid_0's l1: 89.6032
[1000]	valid_0's l1: 88.1026
Did not meet early stopping. Best iteration is:
[1000]	valid_0's l1: 88.1026
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's l1: 171.106
[200]	valid_0's l1: 134.048
[300]	valid_0's l1: 117.574
[400]	valid_0's l1: 109.858
[500]	valid_0's l1: 104.082
[600]	valid_0's l1: 100.278
[700]	valid_0's l1: 97.424
[800]	valid_0's l1: 95.0868
[900]	valid_0's l1: 93.3413
[1000]	valid_0's l1: 91.9314
Did not meet early stopping. Best iteration is:
[1000]	valid_0's l1: 91.9314
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's l1: 175.722
[200]	valid_0's l1: 139.49
[300]	valid_0's l1: 121.311
[400]	valid_0's l1: 112.391
[500]	valid_0's l1: 106.518
[600]	valid_0's l1: 102.207
[700]	valid_0's l1: 99.3826
[800]	valid_0's l1: 97.084
[900]	valid_0's l1: 95.0601
[1000]	valid_0's l1: 93.7467
Did not meet early stopping. Best iteration is:
[1000]	valid_0's l1: 93.7467
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's l1: 167.82
[200]	valid_0's l1: 136.784
[300]	valid_0's l1: 120.865
[400]	valid_0's l1: 111.313
[500]	valid_0's l1: 105.11
[600]	valid_0's l1: 100.987
[700]	valid_0's l1: 97.9447
[800]	valid_0's l1: 95.444
[900]	valid_0's l1: 93.6278
[1000]	valid_0's l1: 92.0425
Did not meet early stopping. Best iteration is:
[1000]	valid_0's l1: 92.0425
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's l1: 170.013
[200]	valid_0's l1: 135.31
[300]	valid_0's l1: 119.482
[400]	valid_0's l1: 111.381
[500]	valid_0's l1: 105.911
[600]	valid_0's l1: 102.399
[700]	valid_0's l1: 99.6551
[800]	valid_0's l1: 97.5994
[900]	valid_0's l1: 95.9213
[1000]	valid_0's l1: 94.3991
Did not meet early stopping. Best iteration is:
[999]	valid_0's l1: 94.388
162988.38254319283 608.7401696880819 288.2676009069608

PermissionError: [Errno 13] Permission denied: 'ccf_car_sales_lgb.csv'

# Improve

## 数据探索

In [4]:
data.sample(10)

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label
16135,450000,SUV,0,6155b214590c66e6,广西,1,2017,1973.0,136.0,3337.0,892.0
3721,110000,Hatchback,0,3e21824be728cbec,北京,3,2016,1562.0,110.0,2245.0,199.0
24553,530000,Sedan,0,a432c483b5beb856,云南,7,2017,214.0,76.0,234.0,101.0
11321,410000,Sedan,0,dff803b4024d261d,河南,9,2016,447.0,334.0,545.0,184.0
23147,110000,Sedan,0,12f8b7e14947c34d,北京,6,2017,1250.0,358.0,2201.0,87.0
26440,210000,Sedan,0,3d7554f1f56dd664,辽宁,9,2017,3792.0,1113.0,2587.0,2147.0
11144,130000,Hatchback,0,b4be3a4917289c82,河北,9,2016,6009.0,72.0,861.0,145.0
4487,230000,Sedan,0,02aab221aabc03b9,黑龙江,4,2016,145.0,243.0,3821.0,80.0
36083,110000,NaN,4470,4a103c30d593fbbe,北京,4,2018,NaN,NaN,NaN,NaN
30266,430000,SUV,0,feabbf46658382b9,湖南,11,2017,3270.0,561.0,2195.0,1187.0

In [5]:
data_after=data.copy()
data_after.head()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label
0,310000,SUV,0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0,292.0
1,530000,SUV,0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0,466.0
2,150000,SUV,0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0,257.0
3,110000,SUV,0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0,408.0
4,510000,SUV,0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0,610.0

In [6]:
data_before=data.copy()
data_before.head()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label
0,310000,SUV,0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0,292.0
1,530000,SUV,0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0,466.0
2,150000,SUV,0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0,257.0
3,110000,SUV,0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0,408.0
4,510000,SUV,0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0,610.0

In [7]:
data_before.to_csv('data_before.csv')

常用统计量观察

In [8]:
import pandas_profiling
from pathlib import Path
profile=data_before.profile_report(title='CCF Car')
profile.to_file(output_file=Path('./databefore.html'))

经观察数字类型数据都是偏态，进行对数变换

In [9]:
skewness=['carCommentVolum','label','newsReplyVolum','popularity']#偏态

In [10]:
for x in skewness:
    data[x+'_log']=np.log1p(data[x])
data.head()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log
0,310000,SUV,0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0,292.0,2.484907,5.680173,4.672829,7.299797
1,530000,SUV,0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0,466.0,2.484907,6.146329,4.672829,7.374629
2,150000,SUV,0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0,257.0,2.484907,5.552960,4.672829,7.299797
3,110000,SUV,0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0,408.0,2.484907,6.013715,4.672829,7.771067
4,510000,SUV,0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0,610.0,2.484907,6.415097,4.672829,8.178358

In [11]:
# 偏度矫正
numeric_dtypes = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
numerics2 = []
for i in data.columns:
    if data[i].dtype in numeric_dtypes:
        numerics2.append(i)
skew_features = data[numerics2].apply(lambda x: skew(x)).sort_values(ascending=False)

In [12]:
#以0.5作为基准，统计偏度超过此数值的高偏度分布数据列，获取这些数据列的index。
high_skew = skew_features[skew_features > 0.5]
skew_index = high_skew.index

#对高偏度数据进行处理，将其转化为正态分布。
#Box和Cox提出的变换可以使线性回归模型满足线性性、独立性、方差齐次以及正态性的同时，又不丢失信息。
for i in skew_index:
    data[i] = boxcox1p(data[i], boxcox_normmax(data[i] + 1))#这是boxcox1p的使用方法，参数的具体意义暂时不解释

## 特征删除与融合

In [13]:
data.head()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log
0,310000,SUV,0.0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0,292.0,2.484907,5.680173,4.672829,7.299797
1,530000,SUV,0.0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0,466.0,2.484907,6.146329,4.672829,7.374629
2,150000,SUV,0.0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0,257.0,2.484907,5.552960,4.672829,7.299797
3,110000,SUV,0.0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0,408.0,2.484907,6.013715,4.672829,7.771067
4,510000,SUV,0.0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0,610.0,2.484907,6.415097,4.672829,8.178358

In [14]:
# 给省份分类,依据https://www.daas-auto.com/newsDe/892.html
province1=['广东','江苏','山东','浙江','河南']
province2=['河北', '四川', '北京']
province3=['上海', '湖北', '湖南', '安徽']
province4=['辽宁', '云南', '陕西', '福建', '贵州','广西','山西','江西','重庆']
province5=['吉林', '黑龙江', '天津', '内蒙古', '新疆', '甘肃']
province6=['海南','宁夏','青海','西藏']

In [15]:
len(data.province.unique())

22

In [16]:
data['province_rank']='0'
for i in range(len(data)):
    if data['province'][i] in province1:
        data['province_rank'][i]='1'
    elif data['province'][i] in province2:
        data['province_rank'][i]='2'
    elif data['province'][i] in province3:
        data['province_rank'][i]='3'
    elif data['province'][i] in province4:
        data['province_rank'][i]='4'
    elif data['province'][i] in province5:
        data['province_rank'][i]='5'
    elif data['province'][i] in province6:
        data['province_rank'][i]='6'
    else:
        data['province_rank'][i]='0'
data.head()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log,province_rank
0,310000,SUV,0.0,3c974920a76ac9c1,上海,1,2016,1479.0,11.0,106.0,292.0,2.484907,5.680173,4.672829,7.299797,3
1,530000,SUV,0.0,3c974920a76ac9c1,云南,1,2016,1594.0,11.0,106.0,466.0,2.484907,6.146329,4.672829,7.374629,4
2,150000,SUV,0.0,3c974920a76ac9c1,内蒙古,1,2016,1479.0,11.0,106.0,257.0,2.484907,5.552960,4.672829,7.299797,5
3,110000,SUV,0.0,3c974920a76ac9c1,北京,1,2016,2370.0,11.0,106.0,408.0,2.484907,6.013715,4.672829,7.771067,2
4,510000,SUV,0.0,3c974920a76ac9c1,四川,1,2016,3562.0,11.0,106.0,610.0,2.484907,6.415097,4.672829,8.178358,2

In [17]:
data['regYear'].unique(),data['regMonth'].unique()

(array([2016, 2017, 2018], dtype=int64),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64))

In [18]:
data.columns

Index(['adcode', 'bodyType', 'id', 'model', 'province', 'regMonth', 'regYear',
       'popularity', 'carCommentVolum', 'newsReplyVolum', 'label',
       'carCommentVolum_log', 'label_log', 'newsReplyVolum_log',
       'popularity_log', 'province_rank'],
      dtype='object')

In [19]:
tmp=pd.array([5]*10)

print(tmp)

<PandasArray>
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
Length: 10, dtype: int32

In [20]:
# 时间分类
data['date_block_num']=0
tmp=pd.array([0]*len(data))
cnts=[]
for year in data['regYear'].unique():
    for month in data[data['regYear']==year]['regMonth'].unique():
        cnts.append(str(year)+'_'+str(month))
for i in range(len(data)):
    data['date_block_num'][i]=cnts.index(str(data['regYear'][i])+'_'+str(data['regMonth'][i]))+1
data.sample(10)

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log,province_rank,date_block_num
821,140000,Sedan,0.0,0797526c057dcf5b,山西,1,2016,516.0,9.0,4481.0,729.0,2.302585,6.593045,8.407825,6.248043,4,1
2714,440000,Sedan,0.0,a28bb927b6fcb33c,广东,3,2016,5180.0,254.0,227.0,3766.0,5.541264,8.234034,5.429346,8.552753,1,3
21371,450000,Sedan,0.0,7245e0ee27b195cd,广西,5,2017,1214.0,283.0,681.0,292.0,5.648974,5.680173,6.525030,7.102499,4,17
18694,430000,Sedan,0.0,7cf283430b3b5e38,湖南,3,2017,3027.0,1050.0,1939.0,1513.0,6.957497,7.322510,7.570443,8.015658,3,15
17057,140000,SUV,0.0,feabbf46658382b9,山西,1,2017,4428.0,239.0,2965.0,406.0,5.480639,6.008813,7.994970,8.395929,4,13
20070,370000,SUV,0.0,8c915fe4632fb9fa,山东,4,2017,3539.0,138.0,1719.0,1812.0,4.934474,7.502738,7.450080,8.171882,1,16
9227,450000,SUV,0.0,a9a43d1a7ecbe75d,广西,7,2016,194.0,329.0,1849.0,151.0,5.799093,5.023881,7.522941,5.273000,4,7
24392,430000,SUV,0.0,bb9fbec9a2833839,湖南,7,2017,2333.0,63.0,98.0,261.0,4.158883,5.568345,4.595120,7.755339,3,19
20562,330000,Sedan,0.0,dff803b4024d261d,浙江,4,2017,853.0,173.0,69.0,562.0,5.159055,6.333280,4.248495,6.749931,1,16
9743,500000,SUV,0.0,346393c2c6305fb1,重庆,8,2016,140.0,292.0,49.0,251.0,5.680173,5.529429,3.912023,4.948760,4,8

In [21]:
def lag_feature(df, lags, col):
    tmp = df[['date_block_num','province','model',col]]
    for i in lags:
        shifted = tmp.copy()
        shifted.columns = ['date_block_num','province','model', col+'_lag_'+str(i)]
        shifted['date_block_num'] += i
        df = pd.merge(df, shifted, on=['date_block_num','province','model'], how='left')
    return df

In [22]:
ts = time.time()
data=lag_feature(data,[1,2,3,6,12],'popularity')
time.time() - ts

0.0827794075012207

In [23]:
data.sample(10)

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log,province_rank,date_block_num,popularity_lag_1,popularity_lag_2,popularity_lag_3,popularity_lag_6,popularity_lag_12
9003,340000,Hatchback,0.0,3e21824be728cbec,安徽,7,2016,1554.0,236.0,2023.0,347.0,5.468060,5.852202,7.612831,7.349231,3,7,1440.0,1473.0,1259.0,1927.0,NaN
23872,150000,SUV,0.0,2a2ab41f8f6ff1cb,内蒙古,7,2017,1161.0,218.0,4006.0,595.0,5.389072,6.390241,8.295798,7.057898,5,19,1364.0,2000.0,1996.0,1637.0,838.0
6415,410000,SUV,0.0,54fc07138d70374c,河南,5,2016,4416.0,24.0,8159.0,554.0,3.218876,6.318968,9.006999,8.393216,1,5,4220.0,5134.0,5812.0,NaN,NaN
916,330000,SUV,0.0,fde95ea242abd896,浙江,1,2016,4955.0,2.0,380.0,1364.0,1.098612,7.218910,5.942799,8.508354,1,1,NaN,NaN,NaN,NaN,NaN
791,230000,SUV,0.0,61e73e32ad101892,黑龙江,1,2016,238.0,72.0,3255.0,397.0,4.290459,5.986452,8.088255,5.476464,5,1,NaN,NaN,NaN,NaN,NaN
841,340000,SUV,0.0,936168bd4850913d,安徽,1,2016,295.0,7.0,67.0,480.0,2.079442,6.175867,4.219508,5.690359,3,1,NaN,NaN,NaN,NaN,NaN
16655,530000,Sedan,0.0,0797526c057dcf5b,云南,1,2017,344.0,147.0,2451.0,160.0,4.997212,5.081404,7.804659,5.843544,4,13,393.0,327.0,362.0,263.0,244.0
31021,530000,Sedan,0.0,6858d6dfe680bdf7,云南,12,2017,1311.0,2191.0,715.0,281.0,7.692570,5.641907,6.573680,7.179308,4,24,1061.0,1138.0,1503.0,1272.0,1795.0
5370,150000,MPV,0.0,17bc272c93f19d56,内蒙古,5,2016,1438.0,0.0,0.0,361.0,0.000000,5.891644,0.000000,7.271704,5,5,1155.0,1484.0,1517.0,NaN,NaN
9410,430000,Sedan,0.0,7023efdab9cedc03,湖南,8,2016,1294.0,53.0,369.0,202.0,3.988984,5.313206,5.913503,7.166266,3,8,1173.0,1073.0,1277.0,1726.0,NaN

In [24]:
ts = time.time()
group = data.groupby(['date_block_num']).agg({'popularity': ['mean']})
group.columns = [ 'date_avg_popularity' ]
group.reset_index(inplace=True)

data = pd.merge(data, group, on=['date_block_num'], how='left')
data['date_avg_popularity'] = data['date_avg_popularity'].astype(np.float16)
data = lag_feature(data, [1], 'date_avg_popularity')
data.drop(['date_avg_popularity'], axis=1, inplace=True)
time.time() - ts

0.0608365535736084

In [26]:
data.sample()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log,province_rank,date_block_num,popularity_lag_1,popularity_lag_2,popularity_lag_3,popularity_lag_6,popularity_lag_12,date_avg_popularity_lag_1
2511,110000,SUV,0.0,fc32b1a017b34efe,北京,2,2016,4138.0,19.0,1400.0,214.0,2.995732,5.370638,7.244942,8.328209,2,2,4857.0,NaN,NaN,NaN,NaN,2476.0

In [27]:
ts = time.time()
group = data.groupby(['date_block_num', 'province']).agg({'popularity': ['mean']})
group.columns = [ 'date_province_avg_popularity' ]
group.reset_index(inplace=True)

data = pd.merge(data, group, on=['date_block_num','province'], how='left')
data['date_province_avg_popularity'] = data['date_province_avg_popularity'].astype(np.float16) 
data = lag_feature(data, [1,2,3,6,12], 'date_province_avg_popularity')
data.drop(['date_province_avg_popularity'], axis=1, inplace=True)
time.time() - ts

0.1336688995361328

In [28]:
data.sample(5)

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log,province_rank,date_block_num,popularity_lag_1,popularity_lag_2,popularity_lag_3,popularity_lag_6,popularity_lag_12,date_avg_popularity_lag_1,date_province_avg_popularity_lag_1,date_province_avg_popularity_lag_2,date_province_avg_popularity_lag_3,date_province_avg_popularity_lag_6,date_province_avg_popularity_lag_12
19526,130000,Sedan,0.0,9c1c7ee8ebdda299,河北,3,2017,1540.0,57.0,3510.0,941.0,4.060443,6.848005,8.163656,7.340187,2,15,1914.0,1631.0,2090.0,2326.0,3101.0,2912.0,3628.0,3142.0,3602.0,3292.0,2920.0
30538,150000,SUV,0.0,af6f4f548684e14d,内蒙古,12,2017,814.0,453.0,2087.0,404.0,6.118097,6.003887,7.643962,6.703188,5,24,860.0,897.0,901.0,825.0,1530.0,2030.0,810.0,803.5,796.0,734.0,1243.0
19099,110000,SUV,0.0,bb9fbec9a2833839,北京,3,2017,3046.0,28.0,68.0,259.0,3.367296,5.560682,4.234107,8.021913,2,15,5537.0,4193.0,4820.0,4822.0,3297.0,2912.0,3568.0,2732.0,3416.0,3154.0,2520.0
27283,110000,MPV,0.0,7aab7fca2470987e,北京,9,2017,536.0,59.0,1584.0,314.0,4.094345,5.752573,7.368340,6.285998,2,21,555.0,529.0,510.0,482.0,564.0,2182.0,2186.0,1904.0,1876.0,1983.0,3154.0
1775,420000,Sedan,0.0,4a103c30d593fbbe,湖北,2,2016,3439.0,307.0,868.0,473.0,5.730100,6.161207,6.767343,8.143227,3,2,2940.0,NaN,NaN,NaN,NaN,2476.0,1996.0,NaN,NaN,NaN,NaN

In [29]:
ts = time.time()
group = data.groupby(['date_block_num', 'model']).agg({'popularity': ['mean']})
group.columns = [ 'date_model_avg_popularity' ]
group.reset_index(inplace=True)

data = pd.merge(data, group, on=['date_block_num','model'], how='left')
data['date_model_avg_popularity'] = data['date_model_avg_popularity'].astype(np.float16) 
data = lag_feature(data, [1,2,3,6,12], 'date_model_avg_popularity')
data.drop(['date_model_avg_popularity'], axis=1, inplace=True)
time.time() - ts

0.14162111282348633

In [32]:
ts = time.time()
group = data.groupby(['date_block_num', 'adcode']).agg({'popularity': ['mean']})
group.columns = [ 'date_adcode_avg_popularity' ]
group.reset_index(inplace=True)

data = pd.merge(data, group, on=['date_block_num','adcode'], how='left')
data['date_adcode_avg_popularity'] = data['date_adcode_avg_popularity'].astype(np.float16) 
data = lag_feature(data, [1,2,3,6,12], 'date_adcode_avg_popularity')
data.drop(['date_adcode_avg_popularity'], axis=1, inplace=True)
time.time() - ts

0.13861489295959473

In [33]:
data.sample()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log,province_rank,date_block_num,popularity_lag_1,popularity_lag_2,popularity_lag_3,popularity_lag_6,popularity_lag_12,date_avg_popularity_lag_1,date_province_avg_popularity_lag_1,date_province_avg_popularity_lag_2,date_province_avg_popularity_lag_3,date_province_avg_popularity_lag_6,date_province_avg_popularity_lag_12,date_model_avg_popularity_lag_1,date_model_avg_popularity_lag_2,date_model_avg_popularity_lag_3,date_model_avg_popularity_lag_6,date_model_avg_popularity_lag_12,date_adcode_avg_popularity_lag_1,date_adcode_avg_popularity_lag_2,date_adcode_avg_popularity_lag_3,date_adcode_avg_popularity_lag_6,date_adcode_avg_popularity_lag_12
25068,320000,SUV,0.0,a9a43d1a7ecbe75d,江苏,7,2017,2285.0,139.0,1158.0,373.0,4.941642,5.924256,7.055313,7.734559,1,19,2256.0,2141.0,1974.0,620.0,716.0,2092.0,3738.0,3754.0,5148.0,4392.0,3664.0,1197.0,1106.0,1018.5,335.5,405.75,3738.0,3754.0,5148.0,4392.0,3664.0

In [34]:
ts = time.time()
group = data.groupby(['date_block_num', 'model','province']).agg({'popularity': ['mean']})
group.columns = [ 'date_model_province_avg_popularity' ]
group.reset_index(inplace=True)

data = pd.merge(data, group, on=['date_block_num','model','province'], how='left')
data['date_model_province_avg_popularity'] = data['date_model_province_avg_popularity'].astype(np.float16) 
data = lag_feature(data, [1], 'date_model_province_avg_popularity')
data.drop(['date_model_province_avg_popularity'], axis=1, inplace=True)
time.time() - ts

0.09378218650817871

In [35]:
data.sample()

,adcode,bodyType,id,model,province,regMonth,regYear,popularity,carCommentVolum,newsReplyVolum,label,carCommentVolum_log,label_log,newsReplyVolum_log,popularity_log,province_rank,date_block_num,popularity_lag_1,popularity_lag_2,popularity_lag_3,popularity_lag_6,popularity_lag_12,date_avg_popularity_lag_1,date_province_avg_popularity_lag_1,date_province_avg_popularity_lag_2,date_province_avg_popularity_lag_3,date_province_avg_popularity_lag_6,date_province_avg_popularity_lag_12,date_model_avg_popularity_lag_1,date_model_avg_popularity_lag_2,date_model_avg_popularity_lag_3,date_model_avg_popularity_lag_6,date_model_avg_popularity_lag_12,date_adcode_avg_popularity_lag_1,date_adcode_avg_popularity_lag_2,date_adcode_avg_popularity_lag_3,date_adcode_avg_popularity_lag_6,date_adcode_avg_popularity_lag_12,date_model_province_avg_popularity_lag_1
23198,320000,Sedan,0.0,dff803b4024d261d,江苏,6,2017,1014.0,311.0,1840.0,696.0,5.743003,6.546785,7.518064,6.922644,1,18,1066.0,896.0,903.0,549.0,404.0,2130.0,3754.0,5148.0,5640.0,4688.0,3482.0,759.5,648.5,633.0,473.5,374.75,3754.0,5148.0,5640.0,4688.0,3482.0,1066.0